# Generated by Django 5.1 on 2026-05-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingplan',
            name='pages_per_day',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
