# Generated by Django 5.1 on 2026-05-09 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_alter_book_pdf_file_alter_useruploadedbook_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIntelligenceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_type', models.CharField(choices=[('self_help', 'Self Help'), ('academic', 'Academic'), ('fiction', 'Fiction'), ('technical', 'Technical'), ('biography', 'Biography'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=20)),
                ('detected_language', models.CharField(default='English', max_length=50)),
                ('complexity_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('classification_raw', models.JSONField(default=dict, help_text='Full classification response from DeepSeek')),
                ('book_brief', models.JSONField(blank=True, help_text='Cached Book Brief: what, who, core argument, top 5 ideas, verdict', null=True)),
                ('brief_generated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('classifying', 'Classifying'), ('structuring', 'Detecting Structure'), ('embedding', 'Building RAG Index'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('embeddings_built', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_profile', to='books.book')),
            ],
            options={
                'verbose_name': 'Book Intelligence Profile',
            },
        ),
        migrations.CreateModel(
            name='BookIntelligenceChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('start_page', models.PositiveIntegerField(default=1)),
                ('end_page', models.PositiveIntegerField(default=1)),
                ('page_range_display', models.CharField(blank=True, max_length=50)),
                ('chapter_hook', models.TextField(blank=True)),
                ('user_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chapters', to='book_intelligence.bookintelligenceprofile')),
            ],
            options={
                'ordering': ['chapter_number'],
                'unique_together': {('profile', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='PageEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('text_content', models.TextField()),
                ('embedding', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_embeddings', to='book_intelligence.bookintelligenceprofile')),
            ],
            options={
                'ordering': ['page_number', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='QAConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_conversations', to='book_intelligence.bookintelligenceprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_qa_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='QAMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('source_pages', models.JSONField(default=list, help_text='Page numbers used for RAG context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='book_intelligence.qaconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChapterIntelligence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('skim', 'Skim Mode'), ('concept', 'Concept Mode'), ('deep', 'Deep Mode'), ('exam', 'Exam Mode')], max_length=10)),
                ('content', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('ai_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_by_mode', to='book_intelligence.bookintelligencechapter')),
            ],
            options={
                'unique_together': {('ai_chapter', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='NotificationContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('morning_hook', models.TextField(blank=True, help_text='7-9am: big idea in 1 sentence')),
                ('midday_concept', models.TextField(blank=True, help_text='12-1pm: key concept or fact')),
                ('afternoon_story', models.TextField(blank=True, help_text='3-5pm: quote, analogy, or story')),
                ('evening_recap', models.TextField(blank=True, help_text='8-10pm: what you learned today')),
                ('chapter_number', models.PositiveIntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='book_intelligence.bookintelligenceprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'profile', 'date')},
            },
        ),
    ]
