# Generated by Django 5.1 on 2026-04-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_pdf_and_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='Show in Recommended section for all users on home screen'),
        ),
    ]
