# Generated by Django 5.1 on 2026-04-23 12:02

import apps.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_is_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload the PDF of this book. Chapters and chunks will be auto-generated.', max_length=255, null=True, upload_to=apps.books.models.book_pdf_upload_path),
        ),
        migrations.AlterField(
            model_name='useruploadedbook',
            name='pdf_file',
            field=models.FileField(max_length=255, upload_to=apps.books.models.user_book_pdf_upload_path),
        ),
    ]
