# Generated by Django 5.1 on 2026-05-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_reading_plan_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='chapter_source',
            field=models.CharField(choices=[('bookmarks', 'PDF Bookmarks'), ('text_toc', 'Text TOC'), ('ai_generated', 'AI Generated'), ('manual', 'Manual Split')], default='manual', help_text='How chapters were detected for this book', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='daily_minutes',
            field=models.PositiveIntegerField(default=30, help_text="User's daily reading time in minutes (15/30/45/60)"),
        ),
        migrations.AlterField(
            model_name='book',
            name='reading_mode',
            field=models.CharField(choices=[('skim', 'Skim'), ('concept', 'Concept'), ('deep', 'Deep'), ('exam', 'Exam')], default='deep', help_text="User's chosen reading mode — drives which summaries are pre-generated", max_length=10),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='day_number',
            field=models.PositiveIntegerField(default=1, help_text='Which reading day this chunk belongs to (1-indexed, sequential across all chapters)'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='words_count',
            field=models.PositiveIntegerField(default=0, help_text='Precomputed word count for scheduling calculations'),
        ),
        migrations.AlterField(
            model_name='readingschedule',
            name='schedule_data',
            field=models.JSONField(default=list, help_text='List of {day, chunk_ids, estimated_minutes, chapter_number, chapter_title}'),
        ),
        migrations.AlterField(
            model_name='readingschedule',
            name='start_date',
            field=models.DateField(help_text='When the user started this reading plan'),
        ),
        migrations.AlterField(
            model_name='useruploadedbook',
            name='processing_stage',
            field=models.CharField(blank=True, default='', help_text='Current pipeline stage name for Flutter status polling', max_length=50),
        ),
        migrations.AlterField(
            model_name='useruploadedbook',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('awaiting_confirm', 'Awaiting Chapter Confirmation'), ('scheduling', 'Building Reading Schedule'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='useruploadedbook',
            name='toc_raw',
            field=models.JSONField(blank=True, default=list, help_text='Raw detected chapters before user confirmation'),
        ),
        migrations.AlterField(
            model_name='useruploadedbook',
            name='total_pages',
            field=models.PositiveIntegerField(default=0, help_text='Total PDF page count, set during Stage 1'),
        ),
    ]
