# Generated by Django 5.1 on 2026-05-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_chapter_source_alter_book_daily_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='end_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='start_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
