# Generated by Django 5.1 on 2026-05-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_chapter_end_page_chapter_start_page'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name='books_readingschedule'
                          AND column_name='updated_at'
                    ) THEN
                        ALTER TABLE books_readingschedule
                        ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
                    END IF;
                END$$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
